variable "region" {}
variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {}
variable "vcn01_cidr_block" {}
variable "vcn01_display_name" {}
variable "vcn01_dns_label" {}
variable "vcn02_cidr_block" {}
variable "vcn02_display_name" {}
variable "vcn02_dns_label" {}